sudo: required
services:
  - docker

before_install:
  - docker build -t mk7077/reactfrontend_travis .

script:
  - docker run -e CI=true mk7077/reactfrontend_travis npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" 
  app: "learn-docker-react"
  env: "LearnDockerReact-env-2"
  bucket_name: "elasticbeanstalk-us-east-1-758436446823"
  bucket_path: "learn-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"